### ISSUE TITLE
TokenMismatchException

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/Android-SingleSignOn#115]
Checkout branch of Notes android app to reproduce: https://github.com/stefan-niedermann/nextcloud-notes/tree/multi-account

Steps to reproduce:

1. Choose Account A
2. Go to settings, add Account B
3. Go back to main activity
4. Until here everything works as expected
5. Go to settings, choose Account A
6. Go back to main activity
7. Receive 

```
com.nextcloud.android.sso.exceptions.TokenMismatchException: Provided authentication token does not match or package name is not permitted to perform this action
    at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequest(AidlNetworkRequest.java:156)
    at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequest(NextcloudAPI.java:119)
    at it.niedermann.owncloud.notes.util.NotesClient.requestServer(NotesClient.java:200)
    at it.niedermann.owncloud.notes.util.NotesClient.getNotes(NotesClient.java:128)
    at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:348)
    at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:278)
    at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:249)
    at android.os.AsyncTask$2.call(AsyncTask.java:288)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)
```

The token is stored in the sqlite database and explicitly set before creating `NextcloudAPI` in `NotesClient`-class on the lines  `81` and `105`.

I debugged and compared them and they seem to be identical to when the accounts were added the first time and in the database.

cc @David-Development @tobiasKaminsky

**Comment by stefan-niedermann** [comment]
Cause was an old version of the files app.
