### ISSUE TITLE
Implement "HEAD" HTTP method

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/Android-SingleSignOn#147]
```

com.nextcloud.android.sso.exceptions.NextcloudUnsupportedMethodException: The requested HTTP Method is not supported yet! Please contact the developers of the Android Single-On Library for Android
    at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:155)
    at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
    at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:200)
    at it.niedermann.owncloud.notes.persistence.NotesClient.getAvatarEtag(NotesClient.java:163)
    at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper.lambda$updateAvatar$1$NoteServerSyncHelper(NoteServerSyncHelper.java:140)
    at it.niedermann.owncloud.notes.persistence.-$$Lambda$NoteServerSyncHelper$ebqrDd5AoK1YIz4nbNy6Gg1L8Wc.run(Unknown Source:2)
    at java.lang.Thread.run(Thread.java:764)
```

**Comment by David-Development** [comment]
Thanks for the request! Maybe you can elaborate a little bit about the use-case? :)

**Comment by stefan-niedermann** [comment]
Concrete use case: I tried to check the `ETag` of an image before downloading the whole payload, to check whether or not the cached version is up to date.

**Comment by desperateCoder** [comment]
For the "PROPPATCH" method, it would be also nice to have the `HTTP ` annotation working, so I can use SSO for webdav requests as well. Or should I open a new issue?

**Comment by desperateCoder** [comment]
@stefan-niedermann  @David-Development @tobiasKaminsky this exception is not thrown in SSO, it is returned by the files app. This is where the stacktrace leads to:
```java

        // Handle Remote Exceptions
        if (response.getException() != null) {
            if (response.getException().getMessage() != null) {
/*## HERE ##*/  throw parseNextcloudCustomException(response.getException());
            }
            throw response.getException();
        }
```
@tobiasKaminsky: any chance, you can add support for `HEAD`, `PROPFIND` and `PROPPATCH`?

**Comment by stefan-niedermann** [comment]
Currently no longer needed by me. Deck & Notes both have a pull-2-refresh mechanism and i decided that it was the easiest way to [simply clear the Glide cache](https://github.com/stefan-niedermann/nextcloud-deck/blob/1.8.1/app/src/main/java/it/niedermann/nextcloud/deck/ui/MainActivity.java#L387-L392) when one triggers this mechanism.
