### ISSUE TITLE
ClassNotfoundException

### ISSUE THREAD

**Issue by fschaupp** [nextcloud/Android-SingleSignOn#253]
Hi!
As in https://github.com/stefan-niedermann/nextcloud-notes/issues/961 stated, I got this exception after adding a new nextloud-account to the Nextcloud Notes App.

```
App Version: 2.16.7
App Version Code: 2016007
App Flavor: fdroid

Files App Version Code: 30130190

---

OS Version: 4.9.186-perf-gef389aa(V12.0.1.0.QDGMIXM)
OS API Level: 29
Device: polaris
Manufacturer: Xiaomi
Model (and Product): Mi MIX 2S (polaris)

---

java.lang.ClassNotFoundException: com.owncloud.android.lib.common.network.CertificateCombinedException
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:682)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1703)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1594)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1872)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1412)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2114)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:557)
	at java.lang.Throwable.readObject(Throwable.java:951)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1066)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2013)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1899)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1412)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2114)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:557)
	at java.lang.Throwable.readObject(Throwable.java:951)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1066)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2013)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1899)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1412)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.deserializeObjectV2(AidlNetworkRequest.java:329)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:167)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.CapabilitiesClient.getCapabilities(CapabilitiesClient.java:64)
	at it.niedermann.owncloud.notes.main.MainActivity.lambda$null$20$MainActivity(MainActivity.java:791)
	at it.niedermann.owncloud.notes.main.-$$Lambda$MainActivity$4HeEjJCK6xYZ8GdVmxdXI3hCjBw.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: com.owncloud.android.lib.common.network.CertificateCombinedException
	... 32 more
```

@stefan-niedermann advised me to move this bug to this repo.

**Comment by tobiasKaminsky** [comment]
Closing as it seems that popup to allow communication was not shown, but seems now to work.
