### ISSUE TITLE
A disabled application results in an unmanageable exception

### ISSUE THREAD

**Issue by matiasdelellis** [nextcloud/Android-SingleSignOn#280]
The Nextcloud server when you access a disabled application, it redirects you to the main page. For example, with the tutorial API.

```
[matias@nube nextcloud]$ curl -v -u user:password -X GET -H "OCS-APIRequest: true" -H "Accept: application/json" https://delellis.com.ar/index.php/apps/notestutorial/api/0.1
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1:443...
* Connected to delellis.com.ar (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=delellis.com.ar
*  start date: Aug 20 21:44:24 2020 GMT
*  expire date: Nov 18 21:44:24 2020 GMT
*  subjectAltName: host "delellis.com.ar" matched cert's "delellis.com.ar"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Server auth using Basic with user 'matias'
> GET /index.php/apps/notestutorial/api/0.1 HTTP/1.1
> Host: delellis.com.ar
> Authorization: Basic bWF0aWFzOnBlbmNpb25hMg==
> User-Agent: curl/7.71.1
> OCS-APIRequest: true
> Accept: application/json
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Date: Mon, 09 Nov 2020 15:38:14 GMT
< Server: Apache/2.4.46 (Fedora) OpenSSL/1.1.1g
< X-Powered-By: PHP/7.4.11
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< Content-Security-Policy: default-src 'self'; script-src 'self' 'nonce-cDd1cURSTVpxc3YzV0MydzRYTSs0SFo2ZnhEOTJuL0lTK0ZIZlhEWjJ0VT06MDgzWlAwQmcrb0t3Q2tEbTB3dHMxeDR2Qm1hWXNCeVFESzhRVHoyMmtxdz0='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';
< Set-Cookie: oc_sessionPassphrase=%2FzjRp3E2YQJ0aYhY8g9obGV%2FJxQIhPzyhAfhSrKuvRQi5S3z9jMpXzC7897B5IpZGAG3BYggEWAiS5Jp%2Fg2YeTGcmP6eZSu96xogK%2BlZW1E2TwUzRLZ3BEYYvif3QRGY; path=/; secure; HttpOnly; SameSite=Lax
< Set-Cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
< Set-Cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
< Set-Cookie: ocs84jb72zk9=og968r5tg9deu4rgevddj2cf4q; path=/; secure; HttpOnly; SameSite=Lax
< Set-Cookie: cookie_test=test; expires=Mon, 09-Nov-2020 16:38:14 GMT; Max-Age=3600
< Strict-Transport-Security: max-age=15552000; includeSubDomains
< Referrer-Policy: no-referrer
< X-Content-Type-Options: nosniff
< X-Download-Options: noopen
< X-Frame-Options: SAMEORIGIN
< X-Permitted-Cross-Domain-Policies: none
< X-Robots-Tag: none
< X-XSS-Protection: 1; mode=block
< Location: https://delellis.com.ar/apps/files/
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
<
* Connection #0 to host delellis.com.ar left intact
```

Maybe this could be attributed directly to nextcloud as an error, however, my problem here is that this results in an exception that I cannot handle. 😞

# Test project:
Again, a small project to demonstrate the bug. Basically I follow [Readme.md](https://github.com/nextcloud/Android-SingleSignOn/blob/master/README.md) with retrofitl, and apply it to the notes tutorial application.

It is just one activity with the button to select the account. When selecting the account, consult the notes, and log the number of notes.

**Source:**
* https://github.com/matiasdelellis/TestRedirectSSO
**Main code:**
* https://github.com/matiasdelellis/TestRedirectSSO/blob/master/app/src/main/java/com/nextcloud/testRedirectSso/MainActivity.java#L90-L109

## Expected result
If the application is not enabled, Just see some log as "Maybe you have the notes tutorial disabled? Error: ..................."

## Result
If the application is not enabled, instead of catching some kind of error, it breaks directly.

**Exception**
```
D/com.nextcloud.android.sso.api.AidlNetworkRequest: copy data from service finished
E/AndroidRuntime: FATAL EXCEPTION: Thread-3
    Process: com.nextcloud.testRedirectSso, PID: 6535
    java.lang.IllegalArgumentException: code < 400: 302
        at retrofit2.Response.error(Response.java:92)
        at com.nextcloud.android.sso.helper.Retrofit2Helper$1.execute(Retrofit2Helper.java:56)
        at com.nextcloud.android.sso.helper.Retrofit2Helper$1$1.run(Retrofit2Helper.java:72)
I/Process: Sending signal. PID: 6535 SIG: 9
```

I can't find any way to catch this error. 😞 

Thanks for all,
Regards,
Matias

**Comment by tobiasKaminsky** [comment]
We should pass the result code and any status to the app…

**Comment by David-Development** [comment]
So apparently Retrofit throws an exception when the return code is below 400. Not sure why.. Can't seem to find docs on why they do that. The line is here: https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/Response.java#L92

**Comment by David-Development** [comment]
@matiasdelellis Thank you for the detailed report and the sample app, it helped a lot to hunt the issue down.
